version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8081"
      - "9230:9230"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run debug

  # an app with monorepo structure
  app2:
    build: app2
    ports:
      - "8082:8081"
      - "9231:9230"
    volumes:
      - ./app2:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run debug
